# Generated by Django 3.0.5 on 2020-04-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200410_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='电话'),
        ),
    ]
